title: Feel the freedom of the road
description: >
  Feeling adventurous? Feeling like you just want to escape? You’re probably, like us, feeling all sorts of things. And perhaps none so more than that feeling of wanderlust, the excitement you get when setting off on an adventure. So, we’ve put together a collection of road trips up and down Britain, from wild coastlines to gorgeous open country, fit for all tastes and styles. From the lesser-travelled to the just plain good, find your upcoming getaway here. We’ve partnered with the AA to get you back on the road, and to start enjoying the adventure all over again.
partner:
  name: The AA
  link: https://www.theaa.com/

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2021/road-trip-escapes" # the subpath of your site, e.g. /blog/
img: "/uk/2021/road-trip-escapes/_assets/img"
css: "/uk/2021/road-trip-escapes/_assets/css"
js: "/uk/2021/road-trip-escapes/_assets/js"

exclude:
  [
    node_modules,
    package.json,
    package-lock.json,
    gulpfile.js,
    tailwind.config.js
  ]
keep_files: [_assets]
plugins:
  - jekyll-pages-directory
  - jekyll-liquify-alt
